apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truck-logistics-frontend-ingress
  namespace: truck-logistics
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/websocket-services: "mosquitto-service"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bpreact.arffy.com
      secretName: arffy-tls
  # Define shared paths block once
  rules:
    - &frontendRules
      host: bpreact.arffy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: truck-logistics-frontend-service
                port:
                  number: 80
          - path: /mqtt
            pathType: Prefix
            backend:
              service:
                name: mosquitto-service
                port:
                  number: 1902
